swagger: "2.0"
info:
  version: 1.0.0
  title: myapp
  description: My cool app
basePath: /api/v1
tags:
  - name: auth
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /product/addproduct:
    post:
      tags:
        - Product
      summary: Add product
      description: Add product
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              title:
                type: string
              price:
                type: number
              specification:
                type: object
                
                  
              various_size:
                type: object
                
              customizable:
                type: array
                items:
                  oneOf:
                   - type: object

                
              images:
                type: object
                
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Successful added product
        401:
          description: Invalid password or username


  /user/getuserdata:
    get:
      tags:
        - User
      summary: Get user data
      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /user/addAddress:
    post:
      tags:
        - User
      summary: Add address
      parameters:
        - in: body
          name: body
          description: Add address
          schema:
            type: object
          properties:
            Address:
              type: string
            pincode:
              type: string
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Return the user data
        404:
          description: User not found / Unauthorized
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Login to the application
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Successful login
        401:
          description: Invalid password or username
  /auth/signin:
    post:
      tags:
        - Auth
      summary: Sign in
      description: Sign in to the application
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              name:
                type: string
              mobile:
                type: string
              email:
                type: string
              password:
                type: string

      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Successful sign in
        401:
          description: Invalid password or username
  /user/becomeaseller:
    post:
      tags:
        - User
      summary: Become a seller
      description: Become a seller
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              shop_name: 
                type : string  
              gst_id : 
               type: string
              pickup_address : 
                type: object

      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Successful became a seller
        401:
          description: Invalid password or username
  
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
